# Generated by Django 3.2.13 on 2022-05-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petrolPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_state', models.FloatField(default=0)),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_size_tank', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('size', models.FloatField()),
                ('id_petrolPump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orlen.petrolpump')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orlen.vehicle')),
            ],
        ),
    ]
