# Generated by Django 3.2.13 on 2022-06-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orlen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='id_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='orlen.vehicle'),
        ),
    ]
